config/routes.rb
Rails.application.routes.draw do
  # resources :listings
  get 'sessions/new'
  get 'users/new'
  get 'static_pages/home'
  get 'static_pages/help'
  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new', as: 'login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy', as: 'logout'
  get '/oauth/callback', to: 'sessions#omniauth'
  post '/oauth/callback', to: 'sessions#omniauth'
  get '/authorize', to: 'sessions#authorize'
  resources :users do
  	resources :devices
    resources :listings do
    	resources :reservations
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :reservations
  belongs_to :user
  has_many :devices


  def self.turn_off_lights(id)
    if listing = Listing.find_by_id(id)
      if listing.token != nil && listing.automation_service == true
        uri = get_uri(listing.token)
        response = HTTParty.put(uri+'/switches/off', headers: {"Authorization" => "Bearer #{listing.token}"})
      end
    end
  end

  def self.get_status_of_lights(token)
    uri = get_uri(token)
    response = HTTParty.get(uri+'/switches', headers: {"Authorization" => "Bearer #{token}"})
    json = JSON.parse(response.body)
    return json
  end

  private
  def self.get_uri(token)
    endpoints_uri = 'https://graph.api.smartthings.com/api/smartapps/endpoints'
    response = HTTParty.get(endpoints_uri, headers: {"Authorization" => "Bearer #{token}"})
    json = JSON.parse(response.body)
    return json[0]['uri']
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :logged_in?
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.preload(:devices).where(user_id: current_user.id)
    @listings.each do |listing|
      if listing.token != nil
        # print('here')
        lights = Listing.get_status_of_lights(listing.token)
        device_hash = {}
        lights.each{|v| device_hash[v['name']] = v['value']}
        listing.devices.each do |device|
          if value = device_hash[device.smart_id]
            device.switch = value == 'off' ? false : true
          end
        end
      end
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user

    respond_to do |format|
      if @listing.save
        format.html { redirect_to [current_user,@listing], notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to [current_user,@listing], notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to user_listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.where(id:params[:id], user_id: current_user.id).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:address,:client_id,:client_secret, :automation_service,{device_ids: []})
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.haml
= form_for [current_user,@listing] do |f|
  - if @listing.errors.any?
    #error_explanation
      %h2= "#{pluralize(@listing.errors.count, "error")} prohibited this listing from being saved:"
      %ul
        - @listing.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :address
    = f.text_field :address,maxlength: 255, class: 'form-control',maxlength: 255
  .field
    = f.label :client_id
    = f.text_field :client_id,maxlength: 255, class: 'form-control',maxlength: 255
  .field
    = f.label :client_secret
    = f.text_field :client_secret,maxlength: 255, class: 'form-control',maxlength: 255
  .field
    = f.label :automation_service
    = f.check_box :automation_service
  .field
    = f.label :devices
    -if @listing.id == nil
      = f.collection_check_boxes(:device_ids, Device.valid_devices, :id, :name)
    - else 
      = f.collection_check_boxes(:device_ids, Device.where('listing_id is NULL OR listing_id = ?',@listing.id), :id, :name, {:selected => @listing.devices.map(&:id)})
  .actions
    = f.submit 'Save'

app/views/listings/edit.html.haml
%h1 Editing listing

= render 'form'

= link_to 'Show', [current_user,@listing]
\|
= link_to 'Back', user_listings_path

app/views/listings/index.html.haml
Listing listings
%table{margin: 5}
  %thead
    %tr
      %th Address
      %th Automation service
      %th Devices
      %th  
      %th
      %th
      %th

  %tbody
    - @listings.each do |listing|
      %tr
        %td= listing.address
        %td= listing.automation_service
        -listing.devices.collect{|d| d.name}
        %td
          - listing.devices.each do |device|
            = "#{device.name} status: #{device.switch ? 'on' : 'off'}"
            %br
        %td= link_to 'Show', [current_user,listing]
        %td= link_to 'Edit', edit_user_listing_path(current_user,listing)
        %td= link_to 'Destroy', [current_user,listing], method: :delete, data: { confirm: 'Are you sure?' }
        %td= link_to 'Authorize SmartThings', authorize_path(listing_id: listing.id)
%br

= link_to 'New Listing', new_user_listing_path

app/views/listings/new.html.haml
%h1 New listing

= render 'form'

= link_to 'Back', user_listings_path

app/views/listings/show.html.haml
%p#notice= notice

%p
  %b Address:
  = @listing.address
%p
  %b Automation service:
  = @listing.automation_service

= link_to 'New Reservation', new_user_listing_reservation_path(current_user,@listing)
= link_to 'Show Reservation', user_listing_reservations_path(listing_id:@listing)
= link_to 'Edit', edit_user_listing_path(@listing)
\|
= link_to 'Back', user_listings_path