config/routes.rb
Rails.application.routes.draw do
  # resources :listings
  get 'sessions/new'
  get 'users/new'
  get 'static_pages/home'
  get 'static_pages/help'
  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new', as: 'login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy', as: 'logout'
  get '/oauth/callback', to: 'sessions#omniauth'
  post '/oauth/callback', to: 'sessions#omniauth'
  get '/authorize', to: 'sessions#authorize'
  resources :users do
  	resources :devices
    resources :listings do
    	resources :reservations
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :name,presence: true,length: {maximum: 50}
    validates :email,presence: true, length: {maximum: 255},
                format: {with: VALID_EMAIL_REGEX},
                uniqueness: {case_sensitive: false}

    has_secure_password
    validates :password, length: { minimum: 6 },presence: true
    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    has_many :listings

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in? , only: [:show]
  def new
    if !logged_in?
      @user = User.new
    end
  end

  def show
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      log_in @user
      redirect_to @user
      # Handle a successful save.
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.haml
%p
%h1 SignUp 

.row
  .col-md-6.col-md-offset-3
    =form_for(@user, url: signup_path) do |f|
      = render 'shared/error_messages'
      =f.label :name
      =f.text_field :name, class: 'form-control',maxlength: 255
      %br
      =f.label :email
      =f.text_field :email, class: 'form-control',maxlength: 255
      %br
      =f.label :password
      =f.password_field :password, class: 'form-control',maxlength: 255
      %br
      =f.label :password_confirmation
      =f.password_field :password_confirmation, class: 'form-control',maxlength: 255
      %br
      =f.submit "Create Account" , class: 'btn btn-primary'
      %br

app/views/users/show.html.haml
.row
  %aside.col-md-4
    %section
      = @user.name
      %br
      .btn-primary.btn.link_button=button_to 'Listings', user_listings_path(user_id: current_user),method: :get
      %br
      %br
      .btn-primary.btn.link_button=button_to "Devices",user_devices_path(user_id: current_user),method: :get