config/routes.rb
Rails.application.routes.draw do
  # resources :listings
  get 'sessions/new'
  get 'users/new'
  get 'static_pages/home'
  get 'static_pages/help'
  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new', as: 'login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy', as: 'logout'
  get '/oauth/callback', to: 'sessions#omniauth'
  post '/oauth/callback', to: 'sessions#omniauth'
  get '/authorize', to: 'sessions#authorize'
  resources :users do
  	resources :devices
    resources :listings do
    	resources :reservations
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :listing
  validates_presence_of :starttime, :endtime
  scope :overlapping, -> (interval){ where("listing_id = ?  AND starttime <= ? AND ? <= endtime", interval.listing_id, interval.endtime, interval.starttime)}
  validate :cannot_overlap_dates
  after_save :create_automation
  # before_save :check_for_conflicts
  def cannot_overlap_dates
    overlaps = Reservation.overlapping(self).count
    # byebug
    if (self.id == nil && overlaps != 0 ) || (self.id != nil && overlaps > 1)
      errors.add(:cannot_overlap_dates,"Dates are overlapping with other reservations")
    end
  end

  def create_automation
    if reservation.listing.automation
        Listing.delay(run_at: self.endtime).turn_off_lights(self.reservation.listing_id)
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :logged_in?
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.preload(:listing).joins(:listing).where(listings: {user_id: current_user.id})
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @listing = Listing.where(id: params[:listing_id],user_id: current_user.id).first
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    @listing = Listing.where(id: params[:listing_id],user_id: current_user.id).first
    @reservation.listing = @listing
    respond_to do |format|
      if @reservation.save
        format.html { redirect_to [current_user,@listing,@reservation], notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to [current_user,@listing,@reservation], notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.joins(:listing).where(id: params[:id], listings: {user_id: current_user.id}).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:starttime, :endtime)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.haml
= form_for [current_user,@listing,@reservation] do |f|
  - if @reservation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@reservation.errors.count, "error")} prohibited this reservation from being saved:"
      %ul
        - @reservation.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :starttime
    = f.datetime_select :starttime
  .field
    = f.label :endtime
    = f.datetime_select :endtime
  .actions
    = f.submit 'Save'

app/views/reservations/edit.html.haml
%h1 Editing reservation

= render 'form'

= link_to 'Show', @reservation
\|
= link_to 'Back', reservations_path

app/views/reservations/index.html.haml
%h1 Listing reservations

%table
  %thead
    %tr
      %th Starttime
      %th Endtime
      %th
      %th
      %th

  %tbody
    - @reservations.each do |reservation|
      %tr
        %td= reservation.starttime
        %td= reservation.endtime
        %td= link_to 'Show', [current_user,reservation.listing,reservation]
        %td= link_to 'Edit', edit_user_listing_reservation_path(current_user,reservation.listing,reservation)
        %td= link_to 'Destroy', [current_user,reservation.listing,reservation], method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Reservation', new_user_listing_reservation_path

app/views/reservations/new.html.haml
%h1 New reservation

= render 'form'

= link_to 'Back', user_listing_reservations_path

app/views/reservations/show.html.haml
%p#notice= notice

%p
  %b Starttime:
  = @reservation.starttime
%p
  %b Endtime:
  = @reservation.endtime

= link_to 'Edit', edit_user_listing_reservation_path(@reservation)
\|
= link_to 'Back', user_listing_reservations_path