config/routes.rb
Rails.application.routes.draw do
  # resources :listings
  get 'sessions/new'
  get 'users/new'
  get 'static_pages/home'
  get 'static_pages/help'
  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new', as: 'login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy', as: 'logout'
  get '/oauth/callback', to: 'sessions#omniauth'
  post '/oauth/callback', to: 'sessions#omniauth'
  get '/authorize', to: 'sessions#authorize'
  resources :users do
  	resources :devices
    resources :listings do
    	resources :reservations
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .container
      = link_to "sample app", root_path, id: "logo"
      %nav
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Home", root_path
          - if logged_in?
            %li= link_to "Users", current_user
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Listings", user_listings_path(user_id: current_user)
                %li= link_to "Devices", user_devices_path(user_id: current_user)
                %li.divider
                %li
                  = link_to "Log out", logout_path, method: :delete
          - else
            %li= link_to "Log in", login_path

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title
      HomeAutomation10</title>
      =csrf_meta_tags
      =csp_meta_tag

      = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
      = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    =render 'layouts/header'
    %br
    %br
    %br
    %br
    .container
      - flash.each do |message_type, message|
        %div{class: "alert alert-#{message_type}"}= message
      = yield